"""Added new corrections for consistency

Revision ID: 00e59e0eb7e0
Revises: db4678d6f4c1
Create Date: 2024-02-17 20:00:11.047819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00e59e0eb7e0'
down_revision: Union[str, None] = 'db4678d6f4c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('name', sa.String(), nullable=True))
    op.create_index(op.f('ix_models_name'), 'models', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_models_name'), table_name='models')
    op.drop_column('models', 'name')
    # ### end Alembic commands ###
