"""Simplifying the camera calibration removing rvtecs and trvts

Revision ID: 2cda2b5be3e7
Revises: ac7304c42805
Create Date: 2024-02-11 21:10:04.786741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2cda2b5be3e7'
down_revision: Union[str, None] = 'ac7304c42805'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calibrationdata', 'rvecs')
    op.drop_column('calibrationdata', 'tvecs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calibrationdata', sa.Column('tvecs', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('calibrationdata', sa.Column('rvecs', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
