"""Changed the calibration model to capture file saving

Revision ID: 38ba2f4221a5
Revises: 9fadec5bbe86
Create Date: 2024-02-17 06:27:09.637789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '38ba2f4221a5'
down_revision: Union[str, None] = '9fadec5bbe86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calibrationdata', sa.Column('calibration_file_path', sa.String(), nullable=False))
    op.drop_column('calibrationdata', 'camera_matrix')
    op.drop_column('calibrationdata', 'distortion_coefficients')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calibrationdata', sa.Column('distortion_coefficients', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('calibrationdata', sa.Column('camera_matrix', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('calibrationdata', 'calibration_file_path')
    # ### end Alembic commands ###
