"""Added new

Revision ID: 3949b9c6663c
Revises: 9ebd9e1c21b6
Create Date: 2024-02-17 21:24:10.168114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3949b9c6663c'
down_revision: Union[str, None] = '9ebd9e1c21b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
