"""Changing ultralytics model and schem

Revision ID: 47ef29d8cec3
Revises: 0e84ff74bd7a
Create Date: 2024-02-19 12:49:52.479720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47ef29d8cec3'
down_revision: Union[str, None] = '0e84ff74bd7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
