"""Added sot

Revision ID: 4dbc3bfdae98
Revises: 9fae274c9a6e
Create Date: 2024-02-18 00:08:05.691928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dbc3bfdae98'
down_revision: Union[str, None] = '9fae274c9a6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_models_filename', table_name='models')
    op.drop_index('ix_models_id', table_name='models')
    op.drop_index('ix_models_name', table_name='models')
    op.drop_table('models')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('models',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('content_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='models_pkey'),
    sa.UniqueConstraint('file_path', name='models_file_path_key')
    )
    op.create_index('ix_models_name', 'models', ['name'], unique=False)
    op.create_index('ix_models_id', 'models', ['id'], unique=False)
    op.create_index('ix_models_filename', 'models', ['filename'], unique=True)
    # ### end Alembic commands ###
