"""Adding the Annotation models files entry and schema

Revision ID: 551220dd017a
Revises: 884c9f2b857d
Create Date: 2024-02-20 09:48:09.104199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '551220dd017a'
down_revision: Union[str, None] = '884c9f2b857d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annotated_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=True),
    sa.Column('annotated_filename', sa.String(), nullable=True),
    sa.Column('annotated_filepath', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_annotated_files_id'), 'annotated_files', ['id'], unique=False)
    op.create_index(op.f('ix_annotated_files_original_filename'), 'annotated_files', ['original_filename'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_annotated_files_original_filename'), table_name='annotated_files')
    op.drop_index(op.f('ix_annotated_files_id'), table_name='annotated_files')
    op.drop_table('annotated_files')
    # ### end Alembic commands ###
