"""Added vehicle details relationship

Revision ID: 5d2e60267cea
Revises: 2790341a7bf6
Create Date: 2024-03-04 19:06:18.530124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d2e60267cea'
down_revision: Union[str, None] = '2790341a7bf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.String(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_details_id'), 'vehicle_details', ['id'], unique=False)
    op.create_index(op.f('ix_vehicle_details_vehicle_id'), 'vehicle_details', ['vehicle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicle_details_vehicle_id'), table_name='vehicle_details')
    op.drop_index(op.f('ix_vehicle_details_id'), table_name='vehicle_details')
    op.drop_table('vehicle_details')
    # ### end Alembic commands ###
