"""Adding Calibration db

Revision ID: 63857d4533f4
Revises: e752718787f2
Create Date: 2024-02-10 06:15:10.542430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63857d4533f4'
down_revision: Union[str, None] = 'e752718787f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calibrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camera_matrix', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('distortion_coefficients', sa.ARRAY(sa.Float()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calibrations_id'), 'calibrations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_calibrations_id'), table_name='calibrations')
    op.drop_table('calibrations')
    # ### end Alembic commands ###
