"""Added vehicle details relation

Revision ID: 64b238d9cf9d
Revises: 5d2e60267cea
Create Date: 2024-03-04 19:34:16.932396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64b238d9cf9d'
down_revision: Union[str, None] = '5d2e60267cea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
