"""Creating a folder for calibration results

Revision ID: 709768121751
Revises: be3229ad4a86
Create Date: 2024-02-12 14:50:52.254856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '709768121751'
down_revision: Union[str, None] = 'be3229ad4a86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('camera',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camera_name', sa.String(), nullable=True),
    sa.Column('camera_model', sa.String(), nullable=True),
    sa.Column('checkerboard_width', sa.Integer(), nullable=True),
    sa.Column('checkerboard_height', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_camera_camera_name'), 'camera', ['camera_name'], unique=False)
    op.create_index(op.f('ix_camera_id'), 'camera', ['id'], unique=False)
    op.drop_table('cameras')
    op.add_column('calibrationdata', sa.Column('camera_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'calibrationdata', 'camera', ['camera_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'calibrationdata', type_='foreignkey')
    op.drop_column('calibrationdata', 'camera_id')
    op.create_table('cameras',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('camera_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('camera_model', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('checkerboard_width', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('checkerboard_height', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='cameras_pkey')
    )
    op.create_index('ix_cameras_id', 'cameras', ['id'], unique=False)
    op.create_index('ix_cameras_camera_name', 'cameras', ['camera_name'], unique=False)
    op.drop_index(op.f('ix_camera_id'), table_name='camera')
    op.drop_index(op.f('ix_camera_camera_name'), table_name='camera')
    op.drop_table('camera')
    # ### end Alembic commands ###
