"""Added vehicle details and heigh in the db

Revision ID: 776f83b4f344
Revises: bda8bf84eed2
Create Date: 2024-03-04 20:56:03.797370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '776f83b4f344'
down_revision: Union[str, None] = 'bda8bf84eed2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
