"""Upload images correction to model

Revision ID: 872667e914a9
Revises: 012d77280f31
Create Date: 2024-02-18 14:30:18.077856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '872667e914a9'
down_revision: Union[str, None] = '012d77280f31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('camera_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'images', 'camera', ['camera_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.drop_column('images', 'camera_id')
    # ### end Alembic commands ###
