"""Changing ultralytics model

Revision ID: 884c9f2b857d
Revises: 47ef29d8cec3
Create Date: 2024-02-19 12:51:26.822433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '884c9f2b857d'
down_revision: Union[str, None] = '47ef29d8cec3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
