"""Set current database state

Revision ID: 9f6ebe2374d5
Revises: 709768121751
Create Date: 2024-02-12 16:49:18.518732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f6ebe2374d5'
down_revision: Union[str, None] = '709768121751'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('camera',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camera_name', sa.String(), nullable=True),
    sa.Column('camera_model', sa.String(), nullable=True),
    sa.Column('checkerboard_width', sa.Integer(), nullable=True),
    sa.Column('checkerboard_height', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_camera_camera_name'), 'camera', ['camera_name'], unique=False)
    op.create_index(op.f('ix_camera_id'), 'camera', ['id'], unique=False)
    op.alter_column('calibrationdata', 'camera_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'calibrationdata', 'camera', ['camera_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'calibrationdata', type_='foreignkey')
    op.alter_column('calibrationdata', 'camera_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_camera_id'), table_name='camera')
    op.drop_index(op.f('ix_camera_camera_name'), table_name='camera')
    op.drop_table('camera')
    # ### end Alembic commands ###
