"""Added somest

Revision ID: 9fae274c9a6e
Revises: 4a39344223c9
Create Date: 2024-02-18 00:00:40.865012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9fae274c9a6e'
down_revision: Union[str, None] = '4a39344223c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('models', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index('ix_models_filename', table_name='models')
    op.create_index(op.f('ix_models_filename'), 'models', ['filename'], unique=True)
    op.create_unique_constraint(None, 'models', ['file_path'])
    op.drop_column('models', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'models', type_='unique')
    op.drop_index(op.f('ix_models_filename'), table_name='models')
    op.create_index('ix_models_filename', 'models', ['filename'], unique=False)
    op.alter_column('models', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
