"""Adding routes for simply upload of images to db for YOLOv8

Revision ID: aabf959454e2
Revises: 72b98652bc0f
Create Date: 2024-02-19 01:07:59.353871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aabf959454e2'
down_revision: Union[str, None] = '72b98652bc0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ultralyticsuploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ultralyticsuploads_id'), 'ultralyticsuploads', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ultralyticsuploads_id'), table_name='ultralyticsuploads')
    op.drop_table('ultralyticsuploads')
    # ### end Alembic commands ###
