"""Adding Calibration changes to db

Revision ID: ac7304c42805
Revises: 35b23c7ac270
Create Date: 2024-02-11 20:10:06.360269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac7304c42805'
down_revision: Union[str, None] = '35b23c7ac270'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calibrationdata', sa.Column('rvecs', sa.JSON(), nullable=True))
    op.add_column('calibrationdata', sa.Column('tvecs', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calibrationdata', 'tvecs')
    op.drop_column('calibrationdata', 'rvecs')
    # ### end Alembic commands ###
