"""Set current database images camera

Revision ID: ba0f99e662e4
Revises: 9f6ebe2374d5
Create Date: 2024-02-13 05:01:56.563581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba0f99e662e4'
down_revision: Union[str, None] = '9f6ebe2374d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('camera_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'images', 'camera', ['camera_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.drop_column('images', 'camera_id')
    # ### end Alembic commands ###
