"""Added vehicle details relations2

Revision ID: bda8bf84eed2
Revises: 64b238d9cf9d
Create Date: 2024-03-04 19:42:01.565990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bda8bf84eed2'
down_revision: Union[str, None] = '64b238d9cf9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('vehicle_details_model_id_fkey', 'vehicle_details', type_='foreignkey')
    op.drop_column('vehicle_details', 'model_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle_details', sa.Column('model_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('vehicle_details_model_id_fkey', 'vehicle_details', 'models', ['model_id'], ['id'])
    # ### end Alembic commands ###
