"""Names were wrong for Matrix and Distortion tables

Revision ID: be3229ad4a86
Revises: 2cda2b5be3e7
Create Date: 2024-02-11 21:26:25.183340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'be3229ad4a86'
down_revision: Union[str, None] = '2cda2b5be3e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calibrationdata', sa.Column('camera_matrix', sa.JSON(), nullable=True))
    op.add_column('calibrationdata', sa.Column('distortion_coefficients', sa.JSON(), nullable=True))
    op.drop_column('calibrationdata', 'distortion')
    op.drop_column('calibrationdata', 'matrix')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calibrationdata', sa.Column('matrix', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('calibrationdata', sa.Column('distortion', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('calibrationdata', 'distortion_coefficients')
    op.drop_column('calibrationdata', 'camera_matrix')
    # ### end Alembic commands ###
