"""Added ML model upload and file store

Revision ID: c03ff7a8c77b
Revises: 38ba2f4221a5
Create Date: 2024-02-17 13:44:02.796688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c03ff7a8c77b'
down_revision: Union[str, None] = '38ba2f4221a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
