"""Added or updated Model

Revision ID: db4678d6f4c1
Revises: fcb0fc4347b4
Create Date: 2024-02-17 19:21:59.367024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db4678d6f4c1'
down_revision: Union[str, None] = 'fcb0fc4347b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
