"""Added more relas

Revision ID: e7651375756e
Revises: 6f636135b2d1
Create Date: 2024-02-16 15:23:52.392143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7651375756e'
down_revision: Union[str, None] = '6f636135b2d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('camera_user_id_fkey', 'camera', type_='foreignkey')
    op.drop_column('camera', 'user_id')
    op.drop_constraint('images_camera_id_fkey', 'images', type_='foreignkey')
    op.drop_constraint('images_user_id_fkey', 'images', type_='foreignkey')
    op.drop_column('images', 'camera_id')
    op.drop_column('images', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('images', sa.Column('camera_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('images_user_id_fkey', 'images', 'users', ['user_id'], ['id'])
    op.create_foreign_key('images_camera_id_fkey', 'images', 'camera', ['camera_id'], ['id'])
    op.add_column('camera', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('camera_user_id_fkey', 'camera', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
