"""Adding Camera 

Revision ID: f03de6a6edc5
Revises: 44b8303e9216
Create Date: 2024-02-11 00:32:39.595910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f03de6a6edc5'
down_revision: Union[str, None] = '44b8303e9216'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calibrationdata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matrix', sa.JSON(), nullable=True),
    sa.Column('distortion', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calibrationdata_id'), 'calibrationdata', ['id'], unique=False)
    #    op.drop_index('ix_cameras_id', table_name='cameras')
    op.drop_table('cameras')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_first_name', table_name='users')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_index('ix_users_last_name', table_name='users')
    op.drop_index('ix_users_username', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_images_filename', table_name='images')
    op.drop_index('ix_images_id', table_name='images')
    op.drop_table('images')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('content_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('upload_timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='images_pkey')
    )
    op.create_index('ix_images_id', 'images', ['id'], unique=False)
    op.create_index('ix_images_filename', 'images', ['filename'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('department', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey')
    )
    op.create_index('ix_users_username', 'users', ['username'], unique=True)
    op.create_index('ix_users_last_name', 'users', ['last_name'], unique=False)
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_users_first_name', 'users', ['first_name'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.create_table('cameras',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('camera_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('camera_model', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('checkerboard_width', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('checkerboard_height', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='cameras_pkey')
    )
    op.create_index('ix_cameras_id', 'cameras', ['id'], unique=False)
    op.create_index('ix_cameras_camera_name', 'cameras', ['camera_name'], unique=False)
    op.drop_index(op.f('ix_calibrationdata_id'), table_name='calibrationdata')
    op.drop_table('calibrationdata')
    # ### end Alembic commands ###
