"""Added ML model upload

Revision ID: f3a403fa69a5
Revises: c03ff7a8c77b
Create Date: 2024-02-17 14:00:06.461522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3a403fa69a5'
down_revision: Union[str, None] = 'c03ff7a8c77b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
